version: '3.8'

services:
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=pass
  #     - POSTGRES_DB=demo

  app:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:pass@db/demo
    # depends_on:
    #   - db
