name: Run UnitTest

on:
  push:
    branches: [main]

jobs:
  deploy-test:
    runs-on: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt install docker-compose -y && sudo docker-compose build --no-cache
      - name: Test with pytest
        run: |
          sudo docker-compose down -v && sudo docker-compose up -d
