name: Build and Deploy to ECR

on:
  push:
    branches:
      - main
env:
  AWS_ECR_REPO: 805071309209.dkr.ecr.us-east-1.amazonaws.com/tax-wizard-ecr
  ECR_REPOSITORY: tax-wizard-ecr # set this to your Amazon ECR repository name
  ECS_CLUSTER: t-w
  ECS_SERVICE: tw
  ECS_TASK_DEFINITION_FAMILY: tax-w1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.AWS_ECR_REPO }}:latest .
          docker tag ${{ env.AWS_ECR_REPO }}:latest ${{ steps.login-ecr.outputs.registry }}:latest
          docker images
          echo
      - name: Push Docker Image to ECR
        run: |
          docker push ${{ env.AWS_ECR_REPO }}:latest

      - name: Register a new revision of the task definition
        run: |
          aws ecs register-task-definition --family $ECS_TASK_DEFINITION_FAMILY --image ${{ env.AWS_ECR_REPO }}:latest

      - name: Fetch Latest Task Definition ARN
        id: fetch-task-def
        run: |
          # Fetch the latest revision of the ECS task definition ARN
          latest_task_def_arn=$(aws ecs describe-services --cluster $ECS_CLUSTER --services $ECS_SERVICE --query 'services[0].taskDefinition' --output text)
          echo "::set-output name=latest_task_def_arn::${latest_task_def_arn}"

      - name: Update ECS Service
        run: |
          # Update ECS service with the latest task definition
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition ${{ steps.fetch-task-def.outputs.latest_task_def_arn }}
