name: Deploy on Dev (Test)

on:
  push:
    branches:
      - '*'

jobs:
  deploy-test:
    runs-on: test

    steps:
      - uses: actions/checkout@v3

      - name: Docker Compose Setup
        run: |
          sudo apt install docker-compose -y && sudo docker-compose build --no-cache
      - name: Deployment
        run: |
          sudo docker-compose down -v && sudo docker-compose up -d
